name = "FinPulse"
client_id = ""
application_url = ""
embedded = true

[access_scopes]
scopes = "read_orders,read_products,read_inventory,read_analytics,read_reports,read_customers"

[auth]
redirect_urls = [ "https://localhost:3000/api/auth", "https://localhost:3000/api/auth/callback" ]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
uri = "/api/webhooks"

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
